### PR TITLE
Added Vertex Light Support to Flat Lit Toon

### PR DESCRIPTION
**Pull request by HelloKitty**
This commit adds working vertex light handling to the Flat Lit Toon shader. Based on the Standard Shader's VertexGIForward function that handles vertex light contribution calculations. It computes the vertex light contribution, if VERTEXLIGHT_ON (which is disabled if lightmapped), and passes it through geom to frag. VERTEXLIGHT_ON sadly can only be conditional in the vert portion. But the passthrough and additive nature makes it not the worst case. The standard shader makes use of this additional output channel (is that the word?) by storing lightmap information in there if lightmapping is being used instead.

I'm abit of a shader newbie so this was a fun little thing to work on and learn this morning!

Anyway, this should address @TCL987 's #25 

Here is a screenshot! Wow so beautiful omg I could cry

### CODE REVIEW

**Comment by HelloKitty** [comment]
Similar to the standard shader, lightmaps can be implemented on top of this too.

**Comment by netri** [comment]
One issue with this is that it makes it look more like standard shader, essentially removes the anime look.
image
If you instead use normalize(i.posWorld) as normalWorld for VertexLightContribution, it feels better.
image

**Comment by HelloKitty** [comment]
I was open to any changes that change how the lighting is applied. Those changes should be easy to make on top of this PR. I don't use this shader nor do I know what the anime feel is so i had expected someone to adjust that if need be.

However this repository seems inactive or dead. So I don't plan to make any changes right now as it would be a waste of time.

**Comment by TCL987** [comment]
@HelloKitty @netri I've merged this into a branch to experiment with. Thank you for your contributions.

**Pull request merged**
